name: Ping Replit

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Replit
        run: curl -s -o /dev/null https://ed755972-1403-4719-84b6-9df9fa3c8beb-00-2oukye6q1btxt.picard.replit.dev:8080/
